version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=xt-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=<%= password %>"
      - "xpack.security.enabled=true"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: <%= esdPath %>
        target: /buf/esd
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kb01
    environment:
      - "I18N_LOCALE=zh-CN"
      - "console.enabled=false"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=<%= password %>"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
